#!/bin/sh

config_dir=$HOME/.config/kitty

colourscheme() {
	# pick a theme
	local new_theme
	if [ -z "$1" ]
	then
		new_theme="$(command ls $config_dir/themes | fzf)"
		if [ -z "$new_theme" ]
		then
			echo -e "\e[1;33mGuess we're not doing that then...\e[0m"
			return 1
		fi
	else
		new_theme="$1"
	fi
	# load new theme
	cat "$config_dir/themes/$new_theme" > $config_dir/theme.conf
	echo $KITTY_PID
	kill -s USR1 $KITTY_PID
	echo -e "\e[1;32mNew theme is $new_theme!\e[0m"
}

opacity() {
	echo "background_opacity $1" > "$config_dir/opacity.conf"
	kill -s USR1 $KITTY_PID
	echo -e "\e[1;32mOpacity is now $1\e[0m"
}

case $1 in
	theme|colourscheme)
		colourscheme $2
		exit
		;;
	opacity|bg)
		opacity $2
		exit
		;;
	*)
		colourscheme
		;;
esac
